#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

# Create mesh
gmsh system/cavityRotatingInnerWall.geo -3 -o system/cavityRotatingInnerWall.msh -format msh2
gmshToFoam system/cavityRotatingInnerWall.msh 
changeDictionary

#------------------------------------------------------------------------------
