#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

# Create mesh
blockMesh
surfaceFeatures -dict system/surfaceFeaturesDict
snappyHexMesh -dict system/snappyHexMeshDict -overwrite

#------------------------------------------------------------------------------
